# Use root/example as user/password credentials
version: '3.1'

services:
  php-env:
    image: php:apache
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - 9000:80
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./db:/docker-entrypoint-initdb.d" #sync persistent sql files container
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1